- name: prepare.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        state: present

    - name: register system and attach subs
      redhat_subscription:
        state:   present
        username: "admin"
        password: "r3dh4t1!"
        auto_attach: true
